FROM node:20-alpine

WORKDIR /app

# 只复制 server 的依赖清单
COPY server/package.json server/yarn.lock ./server/

# 安装 server 依赖
WORKDIR /app/server
RUN yarn install

# 复制 server 源码
COPY server/ ./

EXPOSE 3000
CMD ["yarn", "dev"]
